<a href="https://colab.research.google.com/github/ananyagoyal1/Machine-Learning/blob/main/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn import datasets

# Load the iris dataset
iris = datasets.load_iris()

# Model dataset
X = iris.data
y = iris.target

# Number of attributes
num_attributes = X.shape[1]
print("Number of attributes:", num_attributes)

# Number of instances
num_instances = X.shape[0]
print("Number of instances:", num_instances)

# 1. Initialize a random numpy array using integer values with the shape (3,3,3)
arr = np.random.randint(1, 11, size=(3, 3, 3))
print("\nRandom Array:")
print(arr)

# 2. Perform the broadcasting operation with another integer
scalar = 5
broadcasted_arr = arr + scalar
print("\nBroadcasted Array:")
print(broadcasted_arr)

# 3. Find the max, min, sum, mean and std of the array elements
print("\nArray Statistics:")
print("Maximum:", arr.max())
print("Minimum:", arr.min())
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())

# 4. Get the unique items and counts of the array elements
unique_elements, counts = np.unique(arr, return_counts=True)
print("\nUnique Elements and Counts:")
print("Unique Elements:", unique_elements)
print("Counts:", counts)

# 5. Calculate the MSE using numpy
true_values = X[:10]  # Taking the first 10 instances as true values
predicted_values = np.random.random((10, num_attributes))  # Random predicted values
mse = np.mean((true_values - predicted_values) ** 2, axis=0)
print("\nMean Squared Error (MSE):", mse)


Number of attributes: 4
Number of instances: 150

Random Array:
[[[ 4 10  1]
  [10  8  7]
  [ 2  2  7]]

 [[ 9  1  6]
  [10 10  6]
  [ 5  8  4]]

 [[ 4  4  6]
  [ 5  2  3]
  [ 4  1  8]]]

Broadcasted Array:
[[[ 9 15  6]
  [15 13 12]
  [ 7  7 12]]

 [[14  6 11]
  [15 15 11]
  [10 13  9]]

 [[ 9  9 11]
  [10  7  8]
  [ 9  6 13]]]

Array Statistics:
Maximum: 10
Minimum: 1
Sum: 147
Mean: 5.444444444444445
Standard Deviation: 2.9355210696939795

Unique Elements and Counts:
Unique Elements: [ 1  2  3  4  5  6  7  8  9 10]
Counts: [3 3 1 5 2 3 2 3 1 4]

Mean Squared Error (MSE): [18.19878658  8.71381056  0.9031484   0.25386414]
